```{r}

#libpath<-"/user_data/kalinka/r_packages"
#.libPaths(c(libpath, .libPaths()))
#remotes::install_github("MadsAlbertsen/ampvis2")
#install.packages("cowplot")
library(ggplot2)
library(ampvis2)
library(cowplot)
library(vroom)
library(tidyverse)

```

##Importing ampvis object
```{r}
amp<-readRDS("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/amp_normalise_mmoX_pmoA.rds")
amp$metadata <- amp$metadata %>%
  mutate(mfd_hab2 = gsub("ยง3 mire", "Mire", mfd_hab2)) %>%
  mutate(mfd_hab2 = gsub("Forrest \\(non-habitattype\\)", "Forrest", mfd_hab2))%>%
  mutate(mfd_hab2=gsub("Fen wetland \\(non-habitat type\\)", "Fen wetland", mfd_hab2))%>%
  mutate(mfd_hab2=gsub("Grasslands \\(non-habitat type\\)", "Grasslands",mfd_hab2))%>%
  mutate(mfd_hab3=gsub("Roadside\\?", "Roadside",mfd_hab3))

```


### Subsetting to amoA
```{r}
### One dataframe with amoA ###
tax_vector_amoA <- c("Betaproteobacteria_amoA", "amoA", "Nitrospira_clade_B", "Nitrospira_clade_A")

f <- amp_subset_taxa(amp, tax_vector = tax_vector_amoA, remove = FALSE, normalise = TRUE)
x<-f$tax

f$tax<-f$tax%>%
 mutate(Genus = trimws(str_extract(OTU, "[^;]*$"))) ###Just for easy plotting at "genus = last word" level
f$mfd_hab2 <- ifelse(is.na(f$mfd_hab2), f$mfd_hab1, f$mfd_hab2)

```


####Creating pca for all samples with and without the filter ####

```{r}

#f_soil_sed <- amp_subset_samples(f,
 # mfd_sampletype %in% c("Sediment", "Soil" ))

pca_f<- amp_ordinate(data = f, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_areatype",
            sample_shape_by = "mfd_sampletype",
            opacity = 0.5,
            species_plot = TRUE,
           species_nlabels = 4,
           species_label_taxonomy = "Genus",
           species_label_size = 3.8,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#ad3838", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea",
"#d45828",
"#0092f3",
"#01b5b7",
"#dec7b0",
"#1d0b00"), name = "Habitat")+
scale_shape_discrete(name="Sample Type")+
  labs(title="Ordination of all samples")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))



 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/pca_amoA.png",
       pca_f,
        height = 6,
  width = 9)
```




####Agriculture
```{r}
agri<- amp_subset_samples(f,
  mfd_areatype %in% c("Agriculture"))
#table(agri$metadata$mfd_hab2)

##Combination would make sense is mfd_hab2
##Perhaps dive into Poales, Cereal


pca_agri<- amp_ordinate(data = agri, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3.5,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#99fa07", "#ba73ea", "#f1dd21",
"#073ff5","#1ec3ec","#36bb98","#ca2b2b","#4e772c", "#f507f5"), name = "Habitat", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Agriculture samples")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/pca_amoA_agri.png",
       pca_agri,
        height = 6,
  width = 9)


```

#### Combining some of the natural soil samples ####
```{r}

nat_soil<- amp_subset_samples(f,
  mfd_areatype %in% c("Natural"))

nat_soil <- amp_subset_samples(f,
  mfd_areatype %in% c("Natural"),
  !is.na(mfd_hab2)) 

#Combining heath and scrub and scherrelous scrub; (and rocky habitats and caves?)
nat_scrub_heath_cave<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Sclerophyllus scrub", "Heath and scrub", "Rocky habitats and caves"))

##Combining coastal and dunes;
nat_coast_dune<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Coastal", "Dunes"))

### Combining forrests and grasslands
nat_forrests_grass<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Forrests", "Grassland formations"))


##and just leaving bog, mire fen as is;
nat_bmf<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Bogs, mires and fens"))

pca_nat_coast_dune<- amp_ordinate(data = nat_coast_dune, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d","#1f0060"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Coastal and Dunes")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom", legend.spacing.x = unit(0.6, "cm"), legend.margin = margin(t = 0, r = 0, b = 0, l = 0)) +
  guides(colour = guide_legend(nrow = 2, ncol = 2))

pca_nat_scrub_heath_cave<- amp_ordinate(data = nat_scrub_heath_cave, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab3",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 8,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d","#1f0060"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Scrubs, Heaths, and Rocky habitats")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom", legend.spacing.x = unit(0.6, "cm")) +
  guides(colour = guide_legend(nrow = 2, ncol = 2))

pca_nat_bmf<- amp_ordinate(data = nat_bmf, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 8,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d","#1f0060"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Bogs, Mires, and Fens")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom", legend.spacing.x = unit(0.6, "cm")) +
  guides(colour = guide_legend(nrow = 2, ncol = 2))

pca_nat_forrests_grass<- amp_ordinate(data = nat_forrests_grass, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 8,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d", "#1a0060", "#c26129", "#5fa3ca"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Forrests and Grasslands")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom", legend.spacing.x = unit(0.6, "cm")) +
  guides(colour = guide_legend(nrow = 2, ncol = 3))


p<-plot_grid(pca_nat_bmf, pca_nat_scrub_heath_cave, pca_nat_coast_dune, pca_nat_forrests_grass, nrow = 2, ncol=2)

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/nat__amoA_2x2.png",
       p,
        height = 10,
  width = 13)

###Just one pca for natural soil;

pca_nat_soil<- amp_ordinate(data = nat_soil, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab1",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#a5e73b", "#4d6922", "#240dee", "#1a0060", "#5fa3ca", "#3063d1","#0c486b","#fa7509","#bb2621","#c20d43"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Natural soil samples")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))

   ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/nat_amoA.png",
       pca_nat_soil,
        height = 6,
  width = 10)


##### And making a corresponding heatmap! ####
#I will try to combine the four dataframes instead...
#Combining heath and scrub and scherrelous scrub; (and rocky habitats and caves?)
### Is made locally, deleted from here to not crash
nat_scrub_heath_cave$metadata<-nat_scrub_heath_cave$metadata%>%
mutate(hab_group="Scrubs, Heaths, and Rocky habitats")

nat_coast_dune$metadata<- nat_coast_dune$metadata %>%
mutate(hab_group="Coastal and Dunes")

nat_forrests_grass$metadata<- nat_forrests_grass$metadata %>%
mutate(hab_group="Forrests and Grasslands")

nat_bmf$metadata<- nat_bmf$metadata %>%
mutate(hab_group="Bogs, Mires, and Fens")

nat<-amp_merge_ampvis2(nat_scrub_heath_cave, nat_coast_dune, nat_forrests_grass, nat_bmf, by_refseq = FALSE)
nat$metadata$hab_group


string<-nat$tax %>%
  select(Genus | Species)
genus_string<-arrange(string, Species, decreasing=FALSE)
genus_string<-unlist(genus_string[,"Genus"])

```


###### Doing sediment samples #####

```{r}
#All sediment samples
sediment<- amp_subset_samples(f,
  mfd_sampletype %in% c("Sediment"))
sediment$metadata$mfd_areatype

##Combination would make sense is mfd_hab2 and mfd_areatype (urban/natural)


##Combining salt and freshwater

pca_sediment<- amp_ordinate(data = sediment, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            sample_shape_by = "mfd_areatype",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3.5,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d", "#1a0060", "#c26129", "#5fa3ca"), name = "Habitat", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Sediment samples")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))+
  guides(color = guide_legend(order = 2), shape = guide_legend(order = 1))


#### Then zooming in on the standing freshwater samples!

sta_fresh<- amp_subset_samples(f,
  mfd_hab2 %in% c("Standing freshwater"),
  !is.na(mfd_hab3)) 
#sta_fresh$metadata$mfd_hab3

pca_sta_fresh<- amp_ordinate(data = sta_fresh, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab3",
            sample_shape_by = "mfd_areatype",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 10,
           species_label_taxonomy = "Genus",
           species_label_size = 3.5,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#a5e73b", "#4d6922", "#240dee", "#1a0060", "#5fa3ca", "#3063d1","#0c486b","#fa7509","#bb2621","#c20d43"), name = "Habitat", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Standing freshwater")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))+
  guides(color = guide_legend(order = 2), shape = guide_legend(order = 1))

p<-plot_grid(pca_sediment, pca_sta_fresh, nrow = 2)

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/pca_amoA_sediment_fresh.png",
       p,
        height = 9,
  width = 10)


```
##### And heatmaps for sediment ###
```{r}

#### Because it is the same sample, I simply cannot merge into one object. Instead, I will try to see if I can cut/paste together in a meaningfull way!
sediment$metadata<- sediment$metadata %>%
mutate(hab_group="Sediment samples")

sta_fresh$metadata<- sta_fresh$metadata %>%
mutate(hab_group="Standing freshwater")

string<-sediment$tax %>%
  select(Genus | Species)
genus_string<-arrange(string, Species, decreasing=FALSE)
genus_string<-unlist(genus_string[,"Genus"])


#### The trick will be to make the boxes within the heatmap the same. The number of tax fits, so the rest is just some cutting in powerpoint!
hm_sediment <- amp_heatmap(sediment,
 facet_by = "hab_group",
 group_by = "mfd_hab2",
 tax_aggregate = "Genus",
 tax_show = 27,
 color_vector = c("white", "darkred"),
 plot_colorscale = "log10",
 plot_values = TRUE,
 plot_values_size = 3.5,
 round = 1,
 order_y_by = rev(genus_string),
 min_abundance=0.1,
 max_abundance = 5,
 normalise = FALSE) +
  theme(axis.text.x = element_text(angle = 45, size = 11, vjust = 1),
        axis.text.y = element_text(size = 10),
        legend.position = "right",
        legend.text = element_text(size = 9),
        legend.title = element_text(size=12),
         strip.text = element_text(size = 12, face = "bold"))

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/hm_sed.png",
       hm_sediment,
        height = 9.6,
  width = 8)


hm_fresh <- amp_heatmap(sta_fresh,
 facet_by = "hab_group",
 group_by = "mfd_hab3",
 tax_aggregate = "Genus",
 tax_show = 27,
 color_vector = c("white", "darkred"),
 plot_colorscale = "log10",
 plot_values = TRUE,
 plot_values_size = 3.5,
 round = 1,
 order_y_by = rev(genus_string),
 min_abundance=0.1,
 max_abundance = 5,
 normalise = FALSE) +
  theme(axis.text.x = element_text(angle = 45, size = 11, vjust = 1),
        axis.text.y = element_text(size = 10),
        legend.position = "right",
        legend.text = element_text(size = 9),
        legend.title = element_text(size=12),
         strip.text = element_text(size = 12, face = "bold"))

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/hm_fresh.png",
       hm_fresh,
        height = 10,
  width = 12)

```

#### Agriculture samples #####


```{r}
#All agri samples
agri<- amp_subset_samples(f_no_amoA,
  mfd_areatype %in% c("Agriculture"))
#table(agri$metadata$mfd_hab2)

##Combination would make sense is mfd_hab2
##Perhaps dive into Poales, Cereal

##Agri AmoA
agri_amoA<- amp_subset_samples(f,
  mfd_areatype %in% c("Agriculture"))

pca_agri<- amp_ordinate(data = agri, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3.5,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#99fa07", "#ba73ea", "#f1dd21",
"#073ff5","#1ec3ec","#36bb98","#ca2b2b","#4e772c", "#f507f5"), name = "Habitat", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Agriculture samples - amoA excluded")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))




pca_agri_amoA<- amp_ordinate(data = agri_amoA, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 8,
           species_label_taxonomy = "Genus",
           species_label_size = 3.5,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#99fa07", "#ba73ea", "#f1dd21",
"#073ff5","#1ec3ec","#36bb98","#ca2b2b","#4e772c", "#f507f5"), name = "Habitat", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Agriculture samples - amoA included")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))


p<-plot_grid(pca_agri_amoA, pca_agri, nrow = 2)

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/pca_agri.png",
       p,
        height = 8,
  width = 9)



#### And then diving into the Poales cereal with amoA;
cereal<- amp_subset_samples(f,
  mfd_hab2 %in% c("Poales, Cereal"))
#table(cereal$metadata$mfd_hab3)

pca_cereal_amoA<- amp_ordinate(data = cereal, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3.5,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
            scale_color_manual(values=c("#87b442", "#01ff16", "#355e08",
"#11b18e","#128160","#36a7bb","#2b8aca","#0c48f0", "#660eca",
"#910696","#be159a","#96095b","#f50762","#d81919","#da5724","#f5dd07"), name = "Habitat", na.translate = FALSE)+
  labs(title="Soil samples from cereal fields - amoA included")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/cereal.png",
       pca_cereal_amoA,
        height = 5.5,
  width = 10)

```


#### Urban samples #####


```{r}
#All sediment samples
urban<- amp_subset_samples(f_no_amoA,
  mfd_areatype %in% c("Urban"), mfd_sampletype %in% c("Soil"))
table(urban$metadata$mfd_hab3)

##Combination would make sense is mfd_hab2 shape and mfd_hab3 color


##Combining salt and freshwater

pca_urban<- amp_ordinate(data = urban, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab3",
            sample_shape_by = "mfd_hab2",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 7,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#1eaa11", "#941919", "#03178a"), name = "Habitat", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Urban soil samples")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom", legend.spacing.x = unit(0.6, "cm")) +
  guides(colour = guide_legend(nrow = 1, ncol = 3))


 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/urban_soil.png",
       pca_urban,
        height = 6,
  width = 9)

```

#### Urban heatmap ###

```{r}
urban$metadata<- urban$metadata %>%
mutate(hab_group="Urban soil samples")

string<-sediment$tax %>%
  select(Genus | Species)
genus_string<-arrange(string, Species, decreasing=FALSE)
genus_string<-unlist(genus_string[,"Genus"])


#### The trick will be to make the boxes within the heatmap the same. The number of tax fits, so the rest is just some cutting in powerpoint!
hm_urban <- amp_heatmap(urban,
 facet_by = "hab_group",
 group_by = "mfd_hab3",
 tax_aggregate = "Genus",
 tax_show = 27,
 color_vector = c("white", "darkred"),
 plot_colorscale = "log10",
 plot_values = TRUE,
 plot_values_size = 3.5,
 round = 2,
 order_y_by = rev(genus_string),
 min_abundance=0.025,
 max_abundance = 5,
 normalise = FALSE) +
  theme(axis.text.x = element_text(angle = 45, size = 11, vjust = 1),
        axis.text.y = element_text(size = 10),
        legend.position = "right",
        legend.text = element_text(size = 9),
        legend.title = element_text(size=12),
         strip.text = element_text(size = 12, face = "bold"))

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/hm_urban.png",
       hm_urban,
        height = 9,
  width = 6)
```


################### Old code no longer in use #######################



##### Natural soil 3 x 3 #######

```{r}
nat_soil<- amp_subset_samples(f_no_amoA,
  mfd_areatype %in% c("Natural"))
x<-nat_soil$metadata
table(x$mfd_hab1)
#-- No rocky habitats and caves. So 3x3
nat_bmf<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Bogs, mires and fens"))
nat_coast<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Coastal"))
nat_dune<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Dunes"))
nat_Forrests<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Forrests"))
nat_Freshwater<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Freshwater"))
nat_grass<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Grassland formations"))
nat_heath<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Heath and scrub"))
nat_Saltwater<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Saltwater"))
nat_scrub<- amp_subset_samples(nat_soil,
  mfd_hab1 %in% c("Sclerophyllus scrub"))

pca_nat_coast<- amp_ordinate(data = nat_coast, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Coastal")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")


pca_nat_dune<- amp_ordinate(data = nat_dune, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Dunes")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")

pca_nat_Forrests<- amp_ordinate(data = nat_Forrests, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Forrests")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")


pca_nat_Freshwater<- amp_ordinate(data = nat_Freshwater, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Freshwater")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")

pca_nat_grass<- amp_ordinate(data = nat_grass, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Grassland formation")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")

pca_nat_heath<- amp_ordinate(data = nat_heath, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Heath and scrub")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")

pca_nat_Saltwater<- amp_ordinate(data = nat_Saltwater, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Saltwater")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")

pca_nat_scrub<- amp_ordinate(data = nat_scrub, 
            type = "PCA", 
             transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            #sample_shape_by = "mfd_hab3",
            opacity = 0.6,
            species_plot = TRUE,
           species_nlabels = 15,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea"), name = "", na.translate = FALSE)+
scale_shape_discrete(name="Sample Type")+
  labs(title="Sclerophyllus scrub")+
  theme(plot.title = element_text(hjust=0.5, face="bold"), legend.position = "bottom")




p<-plot_grid(pca_nat_bmf, pca_nat_coast, pca_nat_dune, pca_nat_Forrests, pca_nat_Freshwater, pca_nat_grass, pca_nat_heath, pca_nat_Saltwater, pca_nat_scrub,
nrow = 3, ncol=3)

 
 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/nat_9x9.png",
       p,
        height = 15,
  width = 15)

```




##### Trying constraints #####

```{r}
f_urban <- amp_subset_samples(f,
  mfd_areatype %in% c("Urban"))


rda_fu<- amp_ordinate(data = f_urban, 
            type = "RDA", 
            transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            sample_shape_by = "mfd_hab1",
            opacity = 0.6,
           constrain = c("mfd_hab1"),
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea",
"#d45828",
"#0092f3",
"#01b5b7",
"#dec7b0",
"#1d0b00"), name = "Habitat Class. 2")+
scale_shape_discrete(name="Habitat Class. 1")+
  labs(title="Urban RDA - Constrained by Habitat Class. 1")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))

rda_fu


 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/rda_urban_mmoX_pmoA.png",
       rda_fu,
        height = 6,
  width = 10)


pca_fu<- amp_ordinate(data = f_urban, 
            type = "PCA", 
            transform = "hellinger", 
            sample_color_by = "mfd_hab2",
            sample_shape_by = "mfd_hab1",
            opacity = 0.6,
                        species_plot = TRUE,
           species_nlabels = 17,
           species_label_taxonomy = "Genus",
           species_label_size = 3,
           species_label_color = "black",
           species_rescale = TRUE,
           filter_species=0,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea",
"#d45828",
"#0092f3",
"#01b5b7",
"#dec7b0",
"#1d0b00"), name = "Habitat Class. 2")+
scale_shape_discrete(name="Habitat Class. 1")+
  labs(title="Urban PCA")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))

p<-plot_grid(pca_fu, rda_fu, nrow = 2)
p
 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/urban_pca_rda_mmoX_pmoA.png",
       p,
        height = 8,
  width = 13)

pca_f<- amp_ordinate(data = f_soil_sed, 
            type = "PCA", 
            transform = "hellinger", 
            sample_color_by = "mfd_areatype",
            sample_shape_by = "mfd_sampletype",
            opacity = 0.6,
            size=10) +
  scale_color_manual(values=c("#697e47", "#913636", "#eed70d",
"#1f0060",
"#00c18d",
"#ec60c0",
"#004563",
"#8773ea",
"#d45828",
"#0092f3",
"#01b5b7",
"#dec7b0",
"#1d0b00"), name = "Habitat")+
scale_shape_discrete(name="Sample Type")+
  labs(title="GraftM package with contigs - Constrained by sampletype")+
  theme(plot.title = element_text(hjust=0.5, face="bold"))

pca_f

p<-plot_grid(pca_all, pca_f, ncol = 2)

 ggsave("/user_data/kalinka/GraftM/shallow_23_04_21/R_scripts_and_figures/pca_mmoX_pmoA.png",
       p,
        height = 5,
  width = 18)
```


